### ISSUE TITLE
can not load

### ISSUE THREAD

**Issue by davichang** [nikitakls/yii2-editor-md#1]
when i run “composer require --prefer-dist yii2-editor-md "*"”

it shows “

 [InvalidArgumentException]
  Could not find package yii2-editor-md.

  Did you mean one of these?
      ipaya/yii2-editor.md
      yiier/yii2-editor.md
      anruence/yii2-editor.md
      nikitakls/yii2-editor-md
      xutl/yii2-editor-md-widget
“

**Comment by nikitakls** [comment]
I fix readme, please try now.
composer require nikitakls/yii2-editor-md
